### ISSUE TITLE
redirection should be toward index, not new

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/rails-form_tag-lab#12]
"At a high level, you need to build a form to create a new student, **have the form redirect back to the new view template**, and print out the form params to the screen. Below are a few items to keep in mind:" - README

"you need to have students controller and form redirect to students path which is index" - Abdoul Diallo (after tests passing when switched to index)

    ```
 Prefix Verb URI Pattern             Controller#Action
 students GET  /students(.:format)     students#index
            POST /students(.:format)     students#create
new_student GET  /students/new(.:format) students#new
    student GET  /students/:id(.:format) students#show
```

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
