### ISSUE TITLE
Solution Doesn't Match Instructions

### ISSUE THREAD

**Issue by boostinwrx** [learn-co-curriculum/rails-form_tag-lab#14]
New(view) renders form (view ) in solution branch, not covered in the read-mes

**Comment by drakeltheryuujin** [comment]
Hi there,

I'm having trouble understanding what the issue with this lab or the curriculum is from this question. What exactly is not covered by the READMEs? The instructions should be pretty clear about what functionality is expected. If you're stuck on how to solve this lab, try discussing your issue via the [Ask a Question][AAQ] tool. 

If you do not believe that this issue has been addressed, please re-open this issue. 💙

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
