### ISSUE TITLE
spec/features/student_spec.rb

### ISSUE THREAD

**Issue by nicklunn325** [learn-co-curriculum/rails-form_tag-lab#21]
Was working with a student on this lab and he seemed to be using form_tag correctly and doing exactly as he was asked to do.  Finally compared the spec files of the solution branch and his master branch.  There are small differences on lines 29 and 30 which I have pasted in screenshots below.  I had him change his spec file (which I know students are not supposed to do).  I first tried to alter his code to match what was going on in the spec file but couldn't seem to get it to work.  Not sure if this is an error in the spec or I was just not understanding how to code to what the spec was looking for?

code from spec/features/student_spec.rb:29-30 in solution branch: 
![solution](https://user-images.githubusercontent.com/53533872/76915925-eda5d600-688c-11ea-8d17-962cc09e9707.png)
code from spec/features/student_spec.rb:29-30 in master branch:
![master](https://user-images.githubusercontent.com/53533872/76915964-162dd000-688d-11ea-9a66-8f770d0835fb.png)

**Comment by nicklunn325** [comment]
This is what the error looked like before changing the spec file to match the spec in the solution branch.
Like I said I tried to code to this error but couldn't get it to work. 

![Screen Shot 2020-03-17 at 8 24 10 PM](https://user-images.githubusercontent.com/53533872/76916041-4a08f580-688d-11ea-9702-1401ce23dcda.png)

**Comment by maxwellbenton** [comment]
Hey @nicklunn325,

Thank you for spotting this. Looks like a change to the spec was made in the `master` branch, but never made it to `solution`. I've rebased the solution and updated it - the change in tests does support what is taught in the previous lesson (https://github.com/learn-co-curriculum/rails-form_tag-readme). The previous lesson shows students how to  use `name=student[first_name]` in ERM form elements, but the old solution here was looking for just `'first_name'` 

Everything should be aligned now. Thank you for opening this issue!
