### ISSUE TITLE
Is there a better way to introduce the Create action?

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/rails-form_tag-lab#7]
This lab suffers from the same problem as the previous lesson –– it instructs us to make the `create` action redirect to the `new` action and print out the `params` hash instead of following a more logical/realistic Rails flow and redirecting it to `index` or `show`.

Seems like a less-than-ideal way to introduce students to the `create` action in Rails.

**Comment by gj** [comment]
I think this:
```ruby
# app/controllers/students_controller.rb

def create
  Student.create(first_name: params[:first_name], last_name: params[:last_name])
  redirect_to students_path
end
```
makes more sense than [this](https://github.com/learn-co-curriculum/rails-form_tag-lab/blob/solution/app/controllers/students_controller.rb):
```ruby
def create
  session[:form_params] = params.inspect
  redirect_to new_student_path
end
```

**Comment by AnnJohn** [comment]
'cc @mendelB @PeterBell

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
